### ISSUE TITLE
Add french language

### ISSUE THREAD

**Issue by ManuSquall** [RazorSh4rk/random-word-api#15]
Hello world, thanks you @RazorSh4rk for making this api available, I would like to be able to contribute to also add the French language, is it possible?

**Comment by ManuSquall** [comment]
Can it be run on Windows or WSL ? (trying with Ubuntu but quite suffering 😅) @RazorSh4rk

**Comment by RazorSh4rk** [comment]
Closing this as it's not really an issue. You are welcome to send a PR anytime though!
