### ISSUE TITLE
Add word length as a parameter

### ISSUE THREAD

**Issue by AlexCabezas2018** [RazorSh4rk/random-word-api#19]
Hi, I think it would be nice to add a "lenght" paramenter to the requests in order to get words of size n

For example, if I try to make this request:

     https://random-word-api.herokuapp.com/word?number=1&lenght=5

I would get:
    
    chair

**Comment by RazorSh4rk** [comment]
Thanks for reminding me, it's been in the backlog for a while now, i added it to the board, will do asap

**Comment by RazorSh4rk** [comment]
Added feature :)
