### ISSUE TITLE
Question about API

### ISSUE THREAD

**Issue by RedS-TheUnbeaten** [RazorSh4rk/random-word-api#2]
Is API has bad words? (Sorry for bad english)

**Comment by RazorSh4rk** [comment]
A quick search told me that yes, it has. Do you need a version where you can exclude them?

**Comment by RazorSh4rk** [comment]
I added the option to enable/disable swear words in the response, just add `&swear=0` to the request (or =1, if you want swear words)

**Comment by RedS-TheUnbeaten** [comment]
You are awrsome, but I have a problem. My code can't get "word",how can I make api giving output like this;
} 
word : word
{

**Comment by RazorSh4rk** [comment]
There isnt really a point in doing a `{key: value}` schema because the keys have to be unique
If you only want one word, you can just get `response[0]`, if you have multiple, you can `response.forEach(el => console.log(el))`
