### ISSUE TITLE
Thank you for this tool

### ISSUE THREAD

**Issue by SwatDoge** [RazorSh4rk/random-word-api#20]
Over the years, we've been using this api in many of our projects. It even became a running joke in our friendgroup to add word of the minute to as many things as possible, including:

- SOTTDWOTMRPCS: https://github.com/SwatDoge/Discord-WOTM-RPC-Service
- A Krunker.io map with wotm: https://imgur.com/M13KyBT.png
- Several wotm backgrounds: https://imgur.com/a/kiuVBN4
- (lost) implementations into plutonium T6 and venice unleashed

A simple hats off and thanks for making this project, your work is appericiated!

**Comment by RazorSh4rk** [comment]
Thank you so much, it really means a lot :) I originally made this for a gamejam where i wanted to make something like typing of the dead, but couldnt find anything that would just throw words at you without api keys and registration. Never imagined it would become so popular that i need to enable logging in heroku. Thanks a lot for using it <3
