### ISSUE TITLE
Thanks and hello

### ISSUE THREAD

**Issue by knuckledragger314** [RazorSh4rk/random-word-api#27]
I am currently using your API for a small project I am working on. But, I am working on hosting some version of it myself. Thank you very much. Please let me know if this is ok or if you want me to donate any money. Do you plan to continue to host it for a while? Also, I want to make sure to give you proper credit when/if I get around to hosting my own version. Thank you very much for all the work you've done on it!

**Comment by RazorSh4rk** [comment]
Thanks for using it, if you find it useful then gratitude is really up to you, i'm not asking for any money :) Let me know what your project is, its always nice to see.

I'm gonna be hosting it until heroku eventually dies so dw about that.
