### ISSUE TITLE
Your API is down!

### ISSUE THREAD

**Issue by knuckledragger314** [RazorSh4rk/random-word-api#29]
Is there a problem on your end or Heroku's?

http://random-word-api.herokuapp.com/home

Thanks again for building this.

**Comment by andy5995** [comment]
I just noticed this too.

**Comment by andy5995** [comment]
> Is there a problem on your end or Heroku's?
> 
> http://random-word-api.herokuapp.com/home
> 
> Thanks again for building this.

@knuckledragger314 
If you need a temporary backup, you can use https://random-word-api-aa.herokuapp.com (note that it's the same address but appended with '-aa').

It's generated from [my fork of this project](https://github.com/andy5995/random-word-api). The master branch of my fork is currently even with the master branch of this project.

**Comment by RazorSh4rk** [comment]
Thank you salesforce for making heroku a paid service and not just automatically keeping my apps running despite having my credit card info. I restarted the dynos, its back online now.
