### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by Thundermaker300** [RazorSh4rk/random-word-api#3]
http://random-word-api.herokuapp.com/key?

Returns 500 Sever Error. I am using this for a project and it’s causing an error in my code.

**Comment by RazorSh4rk** [comment]
Weird, the logs said it was a json error in python? I'll look into it, restarted the dyno for now, should be working.

**Comment by Thundermaker300** [comment]
Yeah I got a 500 Internal Server error, appears to be fine now that you restarted it.
