### ISSUE TITLE
API Key lifetime

### ISSUE THREAD

**Issue by tukno** [RazorSh4rk/random-word-api#4]
Hello, does the API key has a 24 hours lifetime? 
Yesterday I generated one API key to use in a bot project and it was working fine, but today I was getting "wrong API key" message as response.

**Comment by RazorSh4rk** [comment]
Yes, it's heroku's bs, it resets the whole app after 24 hours. You can use the master key, `jecgaa` , but i'll probably get rid of auth keys in the future.

**Comment by tukno** [comment]
Ok, thanks for the reply.

**Comment by RazorSh4rk** [comment]
I updated the app, you dont need an api key anymore
